---
version: 1.0.0
name: Nanowrit Labs • Pulp-Fiction Writing Software
description: Use tools and techniques perfected by classic pulp fiction writers to create your masterpiece!
url: https://guides.nanowritlabs.com
repository: https://github.com/nanowrit/guides
timezone: America/Denver
twitter:
  username: NanowritLabs
collections:
  # docs:
  #   permalink: "/:collection/:path/"
  #   output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  guides:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _guides
    type: docs
  values:
    layout: docs
# - scope:
#     path: _posts
#     type: posts
#   values:
#     layout: news_item
- scope:
    path: _guides
    type: guides
  values:
    layout: guides
- scope:
    path: ''
  values:
    image: "/img/jekyll-og.png"
sass:
  style: compressed
strict_front_matter: true
exclude:
- ".gitignore"
- ".jekyll-cache"
- CNAME
- icomoon-selection.json
- readme.md